apiVersion: v2
description: lksg-tool chart
name: lksg-tool
version: 12.5.5
appVersion: "7.0"
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.4.0
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - postgresql
    version: 12.5.5
  - name: pgadmin4
    repository: https://helm.runix.net
    tags:
      - pgadmin4
    version: 1.15.2

# https://github.com/rowanruseler/helm-charts
# https://github.com/bitnami/charts/tree/main/bitnami/postgresql
