nameOverride: ""
fullnameOverride: ""

lksg_tool:
  namespace: lksg-tool
  
  service:
    type: ClusterIP
    protocol: TCP
  ingress:
    ingressPathType: Prefix
    className: nginx
    hostName: lksg.tool.localdev.me
    port: 80
  apps:
    backend:
      image: grafl/lksg-tool-backend
      tag: latest
      path: /api
      port: 8888
      targetPort: 8888
    frontend:
      image: grafl/lksg-tool-frontend
      tag: latest
      path: /
      port: 88
      targetPort: 88
