kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "lksg-tool.fullname" . }}-deployment
  namespace: {{ .Values.lksg_tool.namespace }}
  labels:
    {{- include "lksg-tool.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "lksg-tool.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lksg-tool.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        {{- range $app_name, $app := .Values.lksg_tool.apps }}
        {{- if or (hasPrefix "irs" $app_name) (hasPrefix "backend" $app_name) (hasPrefix "frontend" $app_name) }}
        - name: lksg-tool-{{ $app_name }}
          image: lksg-tool-{{ $app_name }}:{{ $app.tag }}
          ports:
            - containerPort: {{ $app.targetPort }}
              protocol: TCP
        {{- end }}
        {{- end }}
