kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "lksg-tool.fullname" . }}-deployment
  namespace: {{ .Values.lksg_tool.namespace }}
  labels:
    {{- include "lksg-tool.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "lksg-tool.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lksg-tool.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: lksg-tool-base
          image: lksg-tool-base:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
              protocol: TCP
