{{- $chartName := .Chart.Name }}
{{- $fullName := include "lksg-tool.fullname" . }}
{{- $ingressPathType := $.Values.lksg_tool.ingress.ingressPathType  }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "lksg-tool.fullname" . }}-ingress
  namespace: {{ .Values.lksg_tool.namespace }}
  labels:
    {{- include "lksg-tool.labels" . | nindent 4 }}
    application-base: {{ include "lksg-tool.fullname" . }}-base
    application-backend: {{ include "lksg-tool.fullname" . }}-backend
    application-irs: {{ include "lksg-tool.fullname" . }}-irs
    application-frontend: {{ include "lksg-tool.fullname" . }}-frontend
spec:
  ingressClassName: {{ .Values.lksg_tool.ingress.className }}
  rules:
    - host: {{ .Values.lksg_tool.ingress.hostName }}
      http:
        paths:
          #- path: /
          #  pathType: Prefix
          #  backend:
          #    service:
          #      name: {{ include "lksg-tool.fullname" . }}-base-service
          #      port:
          #        number: 8080
          {{- range $app_name, $app := .Values.lksg_tool.apps }}
          {{- if eq $app_name "pgadmin4" }}
          - path: /
          {{- else }}
          - path: {{ $app.path }}
          {{- end }}
            pathType: {{ $ingressPathType }}
            backend:
              service:
                {{- if eq $app_name "pgadmin4" }}
                name: {{ $chartName }}-{{ $app_name }}
                {{- else }}
                name: {{ $fullName }}-{{ $app_name }}-service
                {{- end }}
                port:
                  number: {{ $app.targetPort }}
          {{- end }}
