kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: lksg-tool-localhost
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: lksg.tool.localdev.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lksg-tool
                port:
                  number: 8080
