kind: Service
apiVersion: v1
metadata:
  name: lksg-tool
  namespace: default
  labels:
    app: lksg-tool
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: lksg-tool
  type: ClusterIP
