apiVersion: v1
kind: Service
metadata:
  name: {{ include "lksg-tool.fullname" . }}-backend-service
  namespace: {{ .Values.lksg_tool.namespace }}
  labels:
    {{- include "lksg-tool.labels" . | nindent 4 }}
    application-backend: {{ include "lksg-tool.fullname" . }}-backend
spec:
  type: {{ .Values.lksg_tool.service.type }}
  ports:
    - port: {{ .Values.lksg_tool.apps.backend.port }}
      targetPort: {{ .Values.lksg_tool.apps.backend.targetPort }}
      protocol: {{ .Values.lksg_tool.service.protocol }}
      name: http
  selector:
    {{- include "lksg-tool.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lksg-tool.fullname" . }}-frontend-service
  namespace: {{ .Values.lksg_tool.namespace }}
  labels:
    {{- include "lksg-tool.labels" . | nindent 4 }}
    application-frontend: {{ include "lksg-tool.fullname" . }}-frontend
spec:
  type: {{ .Values.lksg_tool.service.type }}
  ports:
    - port: {{ .Values.lksg_tool.apps.frontend.port }}
      targetPort: {{ .Values.lksg_tool.apps.frontend.targetPort }}
      protocol: {{ .Values.lksg_tool.service.protocol }}
      name: http
  selector:
    {{- include "lksg-tool.selectorLabels" . | nindent 4 }}
